services:
  backoffice:
    image: sslv-nexus.coexya.eu/lunt-backoffice:${VERSION:-latest}
    ports: ["80:80"]
    depends_on:
      - mariadb
      - mailer
      - solr
    volumes:
      - ./lunt-backoffice:/var/www/site
      - ${JOAI_BASE_URI:-/opt}:/opt

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    ports: ["8080:80"]
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${MARIADB_DB}
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    ports: ["3306:3306"]
    volumes:
      - db_data:/var/lib/mysql

  mailer:
    image: mailhog/mailhog:latest
    ports: ["8025:8025"]

  solr:
    image: solr:latest
    environment:
      - SOLR_HOME=/var/solr/data
      - SOLR_LOG_LEVEL=INFO
      #- SOLR_AUTH_TYPE=basic
      #- SOLR_AUTHENTICATION_OPTS=-Dbasicauth=solr:SolrRocks  #Dsolr.auth.enabled=true
    ports: ["8983:8983"]
    volumes:
      - solr_data:/var/solr
      - ${JOAI_BASE_URI}/lunt-solr/data:/var/solr/data
      - ${JOAI_BASE_URI}/lunt-solr/conf:/opt/solr/server/solr/configsets/_default/conf
    command:
      - solr-precreate
      - unt1

volumes:
  db_data:
  solr_data:
  wp_data:
