services:
  backoffice:
    image: sslv-nexus.coexya.eu/lunt-backoffice:${VERSION:-latest}
    env_file: ./.env
    network_mode: "host"
    depends_on:
      - mariadb
      - solr
    volumes:
      - ${JOAI_BASE_URI:-/opt}:/opt
      - ${JOAI_BASE_URI}/lunt-resources/uploads:/var/www/site/public/uploads

  mariadb:
    image: mariadb:11.7.2
    environment:
      MYSQL_DATABASE: ${MARIADB_DB}
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    network_mode: "host"
    volumes:
      - db_data:/var/lib/mysql

  solr:
    image: solr:9.8-slim
    network_mode: "host"
    volumes:
      - ${JOAI_BASE_URI}/lunt-solr/data:/var/solr/data
      - ${JOAI_BASE_URI}/lunt-solr/conf:${SOLR_DEFAULT_CONF}/conf
    command:
      - solr-precreate
      - unt1
      - ${SOLR_DEFAULT_CONF}

volumes:
  db_data:
