services:
  backoffice:
    build:
        context: ./lunt-backoffice
    volumes:
      # La ligne du dessous pour ne pas avoir à recompiler à chaque modification
      - ./lunt-backoffice:/var/www/site
      - ./lunt-resources:/opt/lunt-resources
      - ${UNT_BASE_URI}/lunt-resources/XML:/opt/lunt-resources/XML
      - ${UNT_BASE_URI}/lunt-resources/uploads:/var/www/site/public/uploads

  joai:
    build:
      context: ./lunt-joai

  mailer:
    image: mailhog/mailhog:latest
    network_mode: "host"
