services:
  backoffice:
    build:
        context: ${UNT_BASE_URI}/lunt-backoffice
    volumes:
      # La ligne du dessous pour ne pas avoir à recompiler à chaque modification (mais peut ralentir les perfs)
      - ${UNT_BASE_URI}/lunt-backoffice:/var/www/site
      - ${UNT_BASE_URI}/lunt-resources:/opt/lunt-resources

  joai:
    build:
      context: ${UNT_BASE_URI}/lunt-joai

  mailer:
    image: mailhog/mailhog:latest
    network_mode: "host"
