services:
  backoffice:
    image: sslv-nexus.coexya.eu/lunt-backoffice:${VERSION:-latest}
    ports: ["80:80"]
    depends_on:
      - mariadb
      - mailer
    volumes:
      - ${JOAI_BASE_URI:-/opt/lunt-resources}:/var/www/site/data
    command:
      - chown -R www-data:www-data var
      - php bin/console ap:i

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    ports: ["8080:80"]
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${MARIADB_DB}
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    ports: ["3306:3306"]
    volumes:
      - db_data:/var/lib/mysql

  mailer:
    image: mailhog/mailhog:latest
    ports: ["8025:8025"]

  solr:
    image: solr:latest
    environment:
      - SOLR_HOME=/var/solr/data
      - SOLR_LOG_LEVEL=INFO
    ports: ["8983:8983"]
    volumes:
      - solr_data:/var/solr
      - /opt/lunt-solr:/var/solr/data
    command:
      - solr-precreate
      - unt1

volumes:
  db_data:
  solr_data:
  wp_data:
