version: "3.8"



volumes:
  db_data:

services:
  backoffice:
    build:
      context: ./lunt-backoffice
    ports:
      - '80:80'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MARIADB_DB}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ADMIN_PASSWORD}
    ports:
      - ${MARIADB_PORT}
    volumes:
      - db_data:${MARIADB_DATA}

